### ISSUE TITLE
Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by Toilal** [vue-reactivity/scope#2]
I try to run the example in README, but it fails with this error.

```
$ NODE_OPTIONS='--no-warnings --experimental-vm-modules' node
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> const { effectScope, ref, computed, watch, watchEffect, stop } = await import ('@vue-reactivity/scope')
undefined
> const counter = ref(0)
undefined
>     const scope = effectScope(() => {
...       // computed, watch, watchEffect, effect ran inside the scope will be auto collected
...       const doubled = computed(() => counter.value * 2)
... 
...       watch(doubled, () => console.log(doubled.value))
... 
...       watchEffect(() => console.log('Count: ', doubled.value))
...     })
Count:  0
undefined
>     stop(scope)
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at stop (/home/toilal/projects/carbon-saver/platform.carbon-saver/node_modules/@vue-reactivity/scope/dist/index.js:31:21)
    at /home/toilal/projects/carbon-saver/platform.carbon-saver/node_modules/@vue-reactivity/scope/dist/index.js:31:36
    at Array.forEach (<anonymous>)
    at stop (/home/toilal/projects/carbon-saver/platform.carbon-saver/node_modules/@vue-reactivity/scope/dist/index.js:31:21)
> 
```

**Comment by antfu** [comment]
This project is no longer needed as `@vue/reactivity` now ships `effectScope` API
